[package]
name = "window"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
bevy.workspace = true
winit.workspace = true
anyhow.workspace = true
thiserror.workspace = true

[target.'cfg(target_os = "windows")'.dependencies]
winapi = { version = "0.3", features = ["winuser", "shellscalingapi"] }

[target.'cfg(target_os = "macos")'.dependencies]
cocoa = "0.26"
objc = "0.2"

[target.'cfg(all(unix, not(target_os = "macos")))'.dependencies]
x11 = "2.21"
